modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/Ellemes/expanded-storage/issues/"
license = "multiple"

[[mods]]
modId = "expandedstorage"
version = "${version}"
displayName = "Expanded Storage"
authors = "Ellemes"
logoFile = "icon.png"

[[dependencies.expandedstorage]]
modId = "forge"
mandatory = true
versionRange = "[41.0.64,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedstorage]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedstorage]]
modId = "ellemes_container_lib"
mandatory = true
versionRange = "[2.0.0,)"
ordering = "NONE"
side = "BOTH"
