modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/NinjaPhenix/expanded-storage/issues/"
license = "multiple"

[[mods]]
modId = "expandedstorage"
version = "${version}"
displayName = "Expanded Storage"
authors = "NinjaPhenix"
logoFile = "icon.png"

[[dependencies.expandedstorage]]
modId = "forge"
mandatory = true
versionRange = "[38.0.14,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedstorage]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedstorage]]
modId = "ninjaphenix_container_lib"
mandatory = true
versionRange = "[1.2.7,)"
ordering = "NONE"
side = "BOTH"
