modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/Ellemes/expanded-storage/issues/"
license = "See LICENSE file"

[[mods]]
modId = "expandedstorage"
version = "${version}"
displayName = "Expanded Storage"
authors = "Bucket of Compasses"
logoFile = "icon.png"

[[dependencies.expandedstorage]]
modId = "forge"
mandatory = true
versionRange = "[40.2.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedstorage]]
modId = "minecraft"
mandatory = true
versionRange = "1.18.2"
ordering = "NONE"
side = "BOTH"
