modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/Ellemes/expanded-storage/issues/"
license = "multiple"

[[mods]]
modId = "expandedstorage"
version = "${version}"
displayName = "Expanded Storage"
authors = "Ellemes"
logoFile = "icon.png"

[[dependencies.expandedstorage]]
modId = "forge"
mandatory = true
versionRange = "[40.0.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedstorage]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedstorage]]
modId = "ellemes_container_lib"
mandatory = true
versionRange = "[2.0.0-beta.1,)"
ordering = "NONE"
side = "BOTH"
